spring:
    application.name: beer-api-producer-junit5
    cloud.stream.bindings.output:
        content-type: application/json
        # remove::start[]
        destination: verifications
        # remove::end[]
server.port: ${PORT:8080}
logging:
  level:
    org.springframework.cloud: debug
