spring:
  application.name: beer-api-producer
  cloud.stream.bindings.output-out-0:
    
    destination: verifications
    
server.port: ${PORT:8080}
logging:
  level:
    org.springframework.cloud: debug
