spring:
    application.name: beer-api-producer
    cloud.stream.bindings.output:
        content-type: application/json
        # remove::start[]
        destination: verifications
        # remove::end[]
server.port: ${PORT:8080}